### PR TITLE
WIP: Update from upstream

### PR DESCRIPTION
**Pull request by brysgo**
Progress: It builds locally and in travis. Coverity also passes.

It crashes when I try and run on my android.

### CODE REVIEW

**Comment by kabbi** [comment]
I've updated the code. In the nearest future I'm going to implement configurable screen size / depth / font size and colors

**Comment by brysgo** [comment]
Thanks @kabbi !!! If you need/want help with anything or just need to talk through a challenge let me know. I've been struggling with the keyboard input problem. My bluetooth keyboard kicks my daydream controller and shuts off VR.

**Comment by kabbi** [comment]
I was having a problem like that when keyboard was focusing the `back` button on screen, which is rendered by default for cardboard / daydream apps. I made it unfocusable in my fork, so that it won't be accidentally clicked by keyboard input.
Why do you think it is kicking a daydream controller?

**Comment by brysgo** [comment]
So I just think the Bluetooth keyboard is causing the daydream controller to disconnect. And the daydream controller disconnecting stops VR I think.

**Comment by brysgo** [comment]
But it could be the bug you mentioned too

**Comment by kabbi** [comment]
Btw, what do you think should we draw in the background? Current terminal background color? Black? White? Configurable color? Configurable 360˚ image?

That's how it looks now, with base16-ashes-dark color scheme:
screenshot_20171109-231059

**Comment by brysgo** [comment]
For now, I think it is perfect. Eventually, custom background image would be cool. As for terminal theme, could we just use termux styles?

**Comment by brysgo** [comment]
Also, might be nice to have an option to pin the screen so you could lay flat and code.

**Comment by kabbi** [comment]
Yep, I'm already using termux styles, it works the same for non-vr and vr apps. As for the pinning, it doesn't work great in vr. We can re-center the screen on the sphere around you, with some shortcut. It would not be fixed, but you will be able to put it anywhere. I'll implement it and see how it goes.

**Comment by brysgo** [comment]
Awesome, in daydream there is a button for recentering but it only works on the x axis.

**Pull request closed without merging**
